# Dependencies

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Niranjan
url:              http://niranjanprithviraj.com/
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
plugins:          [jekyll-paginate]
