title:       Niranjan Prithviraj
author:      Niranjan Prithviraj
description: Software engineer writing about tech and ideas.
email:       niranjan.prithviraj@gmail.com
url:         https://niranjanprithviraj.com
baseurl:     ""

twitter_username: nprithvi
github_username:  nbprithv

markdown:  kramdown
permalink: /essays/:title/

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - "*.sh"
